### ISSUE TITLE
arm环境运行异常报错

### ISSUE THREAD

**Issue by zhaobingxiang** [yhl452493373/frpc-panel#4]
amd环境正常
arm环境（frpc-panel-linux-arm64-1.0.0.zip）打开web报下面错误
Get "http://127.0.0.1:0/api/config": dial tcp 127.0.0.1:0: connect: connection refused

系统内核如下： 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux

**Comment by yhl452493373** [comment]
从报错信息来看，你没有配置frpc的管理端口。即`frpc-panel.toml`中没有配置`dashboard_port`
---
**检查你的frpc有没有开启web管理**

如果是低于v0.52.0的版本：
frpc的配置文件`frpc.ini`中，有无如下内容：
```ini
admin_addr = 127.0.0.1
admin_port = 7400
admin_user = admin
admin_pwd = admin
```
---
如果是大于等于v0.52.0的版本：
frpc的配置文件`frpc.toml`中，有无如下内容：

```toml
webServer.addr = "127.0.0.1"
webServer.port = 7400
webServer.user = "admin"
webServer.password = "admin"
```
或
```toml
[webServer]
addr = "127.0.0.1"
port = 7400
user = "admin"
password = "admin"
```
---
如果以上没问题，就检查你`frpc-panel.toml`中的配置，是否包含以下内容：
```toml
# frpc dashboard info
#这个一般不用改。如果frpc-panel和frpc不在同一机器，则需要修改
dashboard_addr = "127.0.0.1"

#如果frp版本低于v0.52.0，这个和 frpc.ini 的 admin_port 相同
#如果frp版本大于等于v0.52.0，这个和 frpc.toml 的 webServer.port相同
dashboard_port = 7400

#如果frp版本低于v0.52.0，这个和 frpc.ini 的 admin_user 相同
#如果frp版本大于等于v0.52.0，这个和 frpc.toml 的 webServer.user相同
dashboard_user = "admin"

#如果frp版本低于v0.52.0，这个和 frpc.ini 的 admin_pwd 相同
#如果frp版本大于等于v0.52.0，这个和 frpc.toml 的 webServer.password相同
dashboard_pwd = "admin"
```
